#! /usr/bin/bash

# Pins interrupts to the isolated or non-isolated cpu core(s).
# Before setting up you could run 'cat /proc/interrupts' to see
# what keywords you can use to hit the particular interrupt.

RED='\033[1;31m'
GRN='\033[1;32m'
YEL='\033[1;33m'
NC='\033[0m'

start() {
echo -e "${YEL}Modify interesting IRQ affinities:${NC}"

    # Pin interrupts to NON-realtime core(s) using its mask
    # CMASK=3
    # grep -E "somekey" /proc/interrupts | cut -d ":" -f 1 | while read -r IRQ; do
    #     echo $CMASK > /proc/irq/$IRQ/smp_affinity
    #     echo -e "IRQ ${GRN}${IRQ}${NC} now has affinity mask ${GRN}${CMASK}${NC}"
    # done

    # Pin interrupts to realtime core(s) using its mask
    CMASK=c
    grep -E "eth0" /proc/interrupts | cut -d ":" -f 1 | while read -r IRQ; do
        echo $CMASK > /proc/irq/$IRQ/smp_affinity
        echo -e "IRQ ${GRN}${IRQ}${NC} now has affinity mask ${GRN}${CMASK}${NC}"
    done
}

stop() {
    echo -e "${YEL}Reset interesting IRQ affinities:${NC}"
    # Allow interrupts to be pinned to any core
    CMASK=f
    grep -E "eth0" /proc/interrupts | cut -d ":" -f 1 | while read -r IRQ; do
        echo $CMASK > /proc/irq/$IRQ/smp_affinity
        echo -e "IRQ ${RED}${IRQ}${NC} now has affinity mask ${RED}${CMASK}${NC}"
    done
}

status() {
    echo -e "${YEL}View interesting IRQ affinities:${NC}"
    # Check interrupts
    grep -E "eth0" /proc/interrupts | cut -d ":" -f 1 | while read -r IRQ; do
        if echo $IRQ | grep -E -v '[[:alpha:]]' > /dev/null
        then
            CMASK=$(cat /proc/irq/$IRQ/smp_affinity)
            echo -e "IRQ ${YEL}${IRQ}${NC} has affinity mask ${YEL}${CMASK}${NC}"
        fi
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
